name: Testx

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install Yarn and FIrebase
      run: |
        npm install -g yarn
    - name: Lint
      run: |
        yarn install
        yarn lint
    - name: Build
      run: |
        yarn install
        yarn build
      env:
        APIKEY: ${{ secrets.APIKEY }}
        AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
        DATABASEURL: ${{ secrets.DATABASEURL }}
        PROJECTID: ${{ secrets.PROJECTID }}
        STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
        MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
        APPID: ${{ secrets.APPID }}
        MEASUREMENTID: ${{ secrets.MEASUREMENTID }}
    - name: Copy
      run: |
        mkdir -p dist/client
        cp -RT src/static dist/client
        cp -RT .nuxt/dist/ dist/client/assets
        mkdir -p dist/server
        cp -RT functions/ dist/server
        cp -R .nuxt/ dist/server/
    - name: install
      run: |
        cd dist/server
        npm install
        cd ../../
